{{- if and .Values.notifications.slack.enabled (not .Values.notifications.slack.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "pvc-autoresizer.fullname" . }}-slack
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pvc-autoresizer.labels" . | nindent 4 }}
type: Opaque
data:
  webhook-url: {{ .Values.notifications.slack.webhookUrl | b64enc | quote }}
{{- end }} 