name: "Main"
on:
  pull_request:
  push:
    branches:
      - "main"
permissions:
  contents: read
  id-token: write

jobs:
  build:
    name: "build"
    runs-on: "ubuntu-22.04"
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: "Set up QEMU"
        uses: docker/setup-qemu-action@99012661954931238ded8c8b007157a8430204e1 # v4.4.0
      - name: "Set up Docker Buildx"
        uses: docker/setup-buildx-action@f87e5991a6d7451dcb8d9637bfbc97413f497069 # v4.4.1
      - uses: ./.github/actions/setup-go
        with:
          go-version-file: "go.mod"
          takumi-guard-bot-id: ${{ vars.TAKUMI_GUARD_BOT_ID }}
      - run: make setup
      - run: make check-uncommitted
      - run: make lint
      - run: make
      - run: make test
      - run: env NO_ANNOTATION_CHECK=true make test
      - run: make image
